args:
  data_name: adamson
  pert_type: gene

  threshold: 0.4
  threshold_co: 0.5
  gene_num: 5000

  source_model_trainable: True
  source_model: False

  batch_size: 32

  lr_anneal_steps: 10000
  log_interval: 10000
  save_interval: 10000

  predict_xstart: True

main:
  from_source: True
  pred_ood: False
